version: 2

machine:
    services:
        - docker

jobs:
    build:
        machine:
            docker_layer_caching: true
        steps:
            - checkout
            - run:
                  name: Build First Stage Container
                  command: |
                      docker build --target=builder -t kleiberd93/budapest-car-sharing-backend:$CIRCLE_SHA1 .

            - run:
                  name: Run tests
                  command: |
                      docker run kleiberd93/budapest-car-sharing-backend:$CIRCLE_SHA1 go test