version: 2

machine:
    services:
        - docker

jobs:
    build:
        machine: true
        steps:
            - checkout
            - run:
                  name: Build First Stage Container
                  command: |
                      make DOCKER_TAG=$CIRCLE_SHA1 docker-build-builder-api

            - run:
                  name: Run tests
                  command: |
                      make DOCKER_TAG=$CIRCLE_SHA1 docker-run-tests-api