kind: Service
apiVersion: v1
metadata:
    name: http-lb
    annotations:
        service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
spec:
    type: LoadBalancer
    externalIPs:
    - "${external_ip}"
    selector:
        app: bcsb-api
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080

---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
    name: budapest-car-sharing-backend-api
spec:
    replicas: 2
    template:
        metadata:
            labels:
                app: bcsb-api
        spec:
            containers:
            - name: budapest-car-sharing-backend-api
              image: kleiberd/budapest-car-sharing-backend-api
              command: ["/go/bin/api"]
              ports:
              - containerPort: 8080